### ISSUE TITLE
Get current user fraction

### ISSUE THREAD

**Issue by absimas** [Triple-T/gradle-play-publisher#1034]
### Problem description
I'm using CI for to stage rollouts for multiple apps. I would now like to release them at separate times thus `userFraction` number would be different based on which was released first.

Is there any way to promote the `userFraction` relative to what is currently set or at least fetch the current `userFraction` for a specific staged rollout track?

**Comment by SUPERCILEX** [comment]
No, this isn't supported and I don't plan on supporting it because GPP can't serve every possible use case. Once you get into custom logic for your release process, I don't think it makes sense to use Gradle anymore. At that point, you should write your own CLI tool tailored to your specific needs.

That said, if you really want to use Gradle you can use [this hack](https://github.com/Triple-T/gradle-play-publisher/issues/878#issuecomment-752821975) and wire up the `userFraction` property to use some output from your task.

Otherwise, here's our internal API surface you can learn from: https://github.com/Triple-T/gradle-play-publisher/tree/4273731c8126cdbf071300882718ec2ae12f3e3c/play/android-publisher/src/main/kotlin/com/github/triplet/gradle/androidpublisher.

**Comment by absimas** [comment]
Thanks for the links!
