### ISSUE TITLE
Can I use this plugin with apk built by my own system (not gradle)

### ISSUE THREAD

**Issue by Dukobpa3** [Triple-T/gradle-play-publisher#109]
Hi.
I'm using Unity3d with teamCity integration.
I want use this plugin for automated deployment to GPlay.
But for now I see to much dependencies to ```com.android.application``` gradle plugin.
I don't want to specify AndroidManifest etc. Also I don't want to build apk with gradle. But for now when I launch task ```publishRelease``` - the system tries to build it's own apk and then publish it.

How can I specify just my own apk and listings?

**Comment by bhurling** [comment]
The purpose of this plugin is to pick up where the official android plugin stops. And that means it picks up the APK created in the tasks before.

There are, however, similar gradle plugins, that might be doing exactly what you want:
* gradle-play-publisher from Seong-Ug Steve Jung: https://github.com/ZeroBrain/gradle-play-publisher
* gradle-play-publisher from Blaž Šolar: https://github.com/blazsolar/gradle-play-publisher
But I am afraid those solutions are not really maintained.

If you are using some form of a CI Server please take a look at the Jenkins plugin to publish to Google Play: https://wiki.jenkins-ci.org/display/JENKINS/Google+Play+Android+Publisher+Plugin

**Comment by shiraji** [comment]
>The purpose of this plugin is to pick up where the official android plugin stops.

I'm sorry if I act like a rude person, but I think this plugin already goes beyond the purpose. Now `bootstrapPlayResources` and `publishListing` should works without running the official android plugin tasks. This is why I sent the pull request #108 and #110. And I am start thinking that it is good idea to have command line options that overwrite settings, like `userFraction`, `errorOnSizeLimit`, or `uploadImages`. And then, if there are these command line options, it may be good idea to have other options like specifying where apk is, what is application id is or any kinds of settings this plugin reads/creates from `build.gradle`. If a lot of users want it, I think we should implement it. At least, someone and I want a function like #108 (check #103) which is not related to the purpose you mentioned.

**Comment by Dukobpa3** [comment]
Thx for the responses.

Also I agree with shiraji. SOLID :)

**Comment by bhurling** [comment]
Hey Guys, I will need some time to figure out where I want to be going with this plugin. You have some really good points here because the API allows to manage lots of stuff the plugin does not yet support. But still I think we need to make sure that we do not bloat the plugin with lots of features that might be conflicting. 

Right now, the plugin is really smart about finding the APK output files for every variant, and with #39, we can even support multiple APKs based on ABI splits. When defining the APK file directly somewhere inside the gradle file, we have to make sure that we don't introduce conflicting behaviour. For example, what happens if someone defines a hard-coded APK file in a multi-variant/multi-build-type project?

I am really sorry if that disappoints you but perhaps you can fork this project and create a lightweight version that does not need the `com.android.application` dependency at all.

**Comment by Dukobpa3** [comment]
> For example, what happens if someone defines a hard-coded APK file in a multi-variant/multi-build-type project?

Just put checker "useAndroidCompiler" into settings.
If ture - than your default provided behaviour.
If false - than I as developer shoul configure each apk for multivariant config.

**Comment by Dukobpa3** [comment]
Another option is using some my parameters as override for default paths and other settings.

**Comment by Dukobpa3** [comment]
I've found maven plugin with behaviour as I want
http://simpligility.github.io/android-maven-plugin/playstore-publisher.html
