### ISSUE TITLE
Error: insufficient data written

### ISSUE THREAD

**Issue by eygraber** [Triple-T/gradle-play-publisher#1099]
### Describe the bug

My nightly release is started failing today with the error:

```
A failure occurred while executing com.github.triplet.gradle.play.tasks.PublishBundle$BundleUploader
         > insufficient data written
```

### How To Reproduce

Upload a bundle

#### Versions

- Gradle Play Publisher: 3.8.4
- Gradle Wrapper: 8.3
- Android Gradle Plugin: 8.2.0-beta03

#### Tasks executed

`publishReleaseBundle`

**Comment by simas-trafi** [comment]
We just ran into this issue as well. This is caused by an incomplete declaration of app's **Financial features**.

The deadline for that was August 31st. And it seems that they started rejecting builds into accounts that are not setup.

To fix this:
1. Go to Google Play Store
2. Open your app
3. Go to App Content (under Policy and programs)
4. Finish Financial Features declaration

<img width="600" alt="image" src="https://github.com/Triple-T/gradle-play-publisher/assets/115018354/73f003a9-6c88-40cd-9d96-3d6565c4614c">

**Comment by sorinirimies** [comment]
We can confirm, we have encountered the same problem.
```
* What went wrong:
> A failure occurred while executing com.github.triplet.gradle.play.tasks.PublishBundle$Processor
   > There was a failure while executing work items
      > A failure occurred while executing com.github.triplet.gradle.play.tasks.PublishBundle$BundleUploader
         > insufficient data written
```

**Comment by eygraber** [comment]
Thanks that was it for us as well

**Comment by casperbang** [comment]
We also ran into this recently, although the problem was with a user-account deletion section recently added/modified for App Content. It would be nice if Google somehow disclosed this in the error for gradle-play-publisher to pick up on and report back, but I guess it's missing on Google's part.

**Comment by LudoFarkas** [comment]
We have this issue too, but it still persists even after declaring financial features and user-account deletion.

Our build generates multiple apks for different ABIs and it seems that 3 out of 4 apks are uploaded correctly. The publish task fails with "insufficient data written" error when uploading the 4th apk. 

@SUPERCILEX , is there a switch to run the task in verbose mode with logging please?

**Comment by Toubap** [comment]
I had the same issue with the `Data safety` section
Once submitted (even in review), it worked

**Comment by SUPERCILEX** [comment]
@LudoFarkas https://docs.gradle.org/current/userguide/logging.html#logLevels debug dumps the network requests IIRC.

**Comment by spencerwhyte** [comment]
@LudoFarkas We are in a similar situation, even after submitting all of our documentation, we are still seeing this issue (but not consistently)

**Comment by LudoFarkas** [comment]
@SUPERCILEX , thanks for the tip. It might have occurred to me.

However, I'm quite sure the problem is not just the incomplete store listing. Our store listing is updated according to the comments above, and the store console does not show any issues. 
In our case, there are 4 APKs to upload due to different ABIs. The sizes of the apks are from 70 to around 100 MB.  So 'gradle-play-publisher' tries to upload 4 APKs and 4 times the same mapping = 8 files. 

Here are my observations after setting the gradle log level to '--info' and observing the task multiple times:

- The number of failed uploads is random. Sometimes just 1 file fails, sometimes 4. Once (after manually deleting the mapping), the task uploaded all APKs successfully.
- There are a lot of responses with http code 308. That is expected, due to resumable file transfers.
- But there are a couple of http 401 responses with a subsequent reauthentication.
- I believe the uploads do not resume correctly after the auth and fail with insufficient data written.
- The count of authentication calls is the same as the count of failed uploads.
- I do not see a subsequent request with the same upload ID to the response with code 308, that happened prior to the authentication.

So, if the gradle error is:

`> A failure occurred while executing com.github.triplet.gradle.play.tasks.PublishApk$Processor
   > There were multiple failures while executing work items
      > A failure occurred while executing com.github.triplet.gradle.play.tasks.PublishApk$ApkUploader
         > insufficient data written
      > A failure occurred while executing com.github.triplet.gradle.play.tasks.PublishApk$ApkUploader
         > insufficient data written
      > A failure occurred while executing com.github.triplet.gradle.play.tasks.PublishApk$ApkUploader
         > insufficient data written
`

with 3 failed uploads, then there were 3 authentification calls during the task execution.

@SUPERCILEX , could you please have a look at it? Should I create a new issue?

**Comment by eygraber** [comment]
I'm reopening because this started happening again after filling out all required forms in the console and publishing that.

**Comment by xserxses** [comment]
Confirming: We are affected as well

**Comment by trevjonez** [comment]
Even seeing where some uploads work and others fail inside the same invocation of gradle.
![image](https://github.com/Triple-T/gradle-play-publisher/assets/5386503/70f71f89-f89b-46f2-8abe-a60591a94608)

The stark difference in time spent before getting that error seems smelly to me.

**Comment by ursusursus** [comment]
We're seeing this as well. Is this a google issue?

**Comment by mivittek** [comment]
Howdy there! 

sadly i am seeing same issue in my  project :( Listing in play store looks fine
```
> A failure occurred while executing com.github.triplet.gradle.play.tasks.PublishApk$Processor
    > There were multiple failures while executing work items
       > A failure occurred while executing com.github.triplet.gradle.play.tasks.PublishApk$ApkUploader
             > insufficient data written
```

Any more ideas please ?

**Comment by Vlado24** [comment]
same here 🤔😢

**Comment by spencerwhyte** [comment]
I just finally got my act together and reached out to Google, I'll keep you posted when I hear back.

**Comment by eygraber** [comment]
I contacted Google yesterday. They said they need time to look into it. I pointed them to this issue, but the more reports they get, the more real it will be to them.

**Comment by Fenris77** [comment]
Google seems to have fixed something in the meantime, because my apps got finally uploaded after many tries in the last three days.

**Comment by LudoFarkas** [comment]
I too can confirm that all of our uploads were successful yesterday.

**Comment by cyberdreamandroid** [comment]
Working again. What a relief 👍

**Comment by sorinirimies** [comment]
Confirming things are working again. The price for depending on centralized entities for our products.
