### ISSUE TITLE
Play Games Services Listing

### ISSUE THREAD

**Issue by FallenRiteMonk** [Triple-T/gradle-play-publisher#111]
Hy,

first of all I love this plugin, but I would love to see it also supporting play games services!
Sadly I have no experience with creating a gradle plugin/task, plus the project seems to be lacking on some contribution guidelines/introduction.
If somebody would be willing to implement this feature or give me some start up help with extending it by my self (like: how I would implement and test, where to hook into the existing code,...) I would really appreciate it and would try to get my hands dirty by my self

Thanks

**Comment by shiraji** [comment]
@bhurling correct me if I am wrong.

I don't have any experience with developing games so I cannot help you with how and where to change (I don't even know what do you mean "Play Games Services Listing"...) However, I can explain how to build and test this library.

This library is using gradle to build and test. The command you want to run tests is `./gradlew test`. There are lots of unit testing in `src/test` directories. It won't actually call publisher api, only mocking it. In case, you really want to call the publisher api, after `./gradlew build`, there is `gradle-play-publisher-x.y.z.jar` in `build/libs`. Put the jar file to actual android project's `libs` folder with this build.gradle

```groovy
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath('com.google.apis:google-api-services-androidpublisher:v2-rev19-1.20.0') {
            exclude group: 'com.google.guava', module: 'guava-jdk5'
        }
        classpath 'commons-lang:commons-lang:2.6'
        classpath 'commons-io:commons-io:1.4'

        classpath files('../libs/gradle-play-publisher-1.1.4.jar') // latest version is 1.1.4.

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

apply plugin: 'com.android.application'
apply plugin: 'com.github.triplet.play'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "your-application-id"
        minSdkVersion 14
        targetSdkVersion 23
        versionCode 1
        versionName "1.0.0"
    }

    signingConfigs {
        release {
            // change these
            storeFile file("storeFile")
            storePassword "storePassword"
            keyAlias "keyAlias"
            keyPassword "keyPassword"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.0.1'
}

play {
    jsonFile file('keys.json')
    userFraction = 0.05
    track = 'rollout'
// in case you want to use p12 file
//    serviceAccountEmail = ''
//    pk12File = file('key.p12')
}
```

I don't have good way to actual testing for this plugin. I created a test project in my private Google Play account and testing this plugin with the actual app.

**Comment by bhurling** [comment]
@FallenRiteMonk: This plugin is using the Google Play Developer API under the hood. I don't think there is any support for games services, yet. Perhaps you can add some details on what exactly you want to update via this plugin. Please also take a look at the [API Reference](https://developers.google.com/android-publisher/api-ref/). I don't see any API resources related to games services.

As for contributions: I really appreciate all the help from you guys. I will add a section to the README for details.

I am currently testing new stuff like so:
1. Change `VERSION_NAME` in `gradle.properties` to something like `1.1.5-SNAPSHOT`
2. Hack, hack, hack
3. Run `./gradlew install` to install the plugin into the local maven repository

And then I am configuring a real published app to use the latest and greatest:
4. Add `mavenLocal()` to the buildscript repositories
5. Change the version code for the buildscript dependency to `1.1.5-SNAPSHOT`

As for the tests: @shiraji is right. The unit tests do not actually make network requests. I am not really happy with the state of the tests right now, because the really interesting stuff cannot be tested this way. We really need to think about extracting the plugin logic from the actual API requests.

**Comment by FallenRiteMonk** [comment]
@shiraji thanks for the info!
@bhurling what I want to edit is the names and descriptions for achievements and leaderboards.
I know that the Google Play Developer API doesn't have anything for the games, but there is a special API for it: 
https://developers.google.com/games/services/publishing/api/index
https://developers.google.com/games/services/publishing/quickstart

**Comment by mars3142** [comment]
There is a new(?) API for it -> https://developers.google.com/games/services/publishing/

**Comment by gtcompscientist** [comment]
Happy to see how this would integrate with the plugin, I have some experience with the Play Games Services.

**Comment by SUPERCILEX** [comment]
FYI, docs:
- https://developers.google.com/games/services/publishing/
- https://developers.google.com/resources/api-libraries/documentation/gamesManagement/v1management/java/latest/overview-summary.html

**Comment by SUPERCILEX** [comment]
Closing due to lack of response. With that said, I'd be very happy to reopen and discuss how we can better support games.
