### ISSUE TITLE
Replace APK within same track

### ISSUE THREAD

**Issue by jtuchek** [Triple-T/gradle-play-publisher#135]
Is it a possibility to replace APKs within the same track without any type of promotion to the next channel. 

I'm having difficulties right now doing this (outside of production). So right now I've got an application in production that is deploying just fine - I'd like to also host the beta and alpha versions as separate applications entires in the play store (with their own unique applicationId and closed tester invites).

So there are 3 separate applications:
Production - APK in production track
Beta - APK in beta track w/ closed testers
Alpha - APK in alpha track w/ closed testers

After bumping the versionCode and versionName appropriately, invoking publishApkAlpha or publishApkBeta the Google Play Publishing API will return a _multiApkShadowedActiveApk_ excpetion

`{
  "code" : 403,
  "errors" : [ {
    "domain" : "androidpublisher",
    "message" : "Version 8 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes.",
    "reason" : "multiApkShadowedActiveApk"
  } ],
  "message" : "Version 8 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes."
}`

This doesn't really reflect the behavior of the developer console because I could take that generated artifact and drop it in to update it without receiving the same exception. I could promote those builds to the next track - but in an attempt to keep those out of the public listing, I'd rather not do that.

If you have an idea on how to make this work, but don't have the time, let me know if there's a way to contribute this functionality - I've been reading through the Publishing API but haven't found what I'm looking for yet to accomplish this.

**Comment by bhurling** [comment]
Related to #121.

The Web Interface behaves a bit differently in the simple mode because it automatically does the following to steps in sequence:

1. Remove old APK version code from alpha track
2. Set newly uploaded APK version code as the only one in alpha track

The plugin is currently more behaving like the expert mode where we just add the new version code to the alpha track (and then have to version codes in alpha). We have to make the decision whether we want to be as flexible as the expert mode (then we need a bunch of tasks) or as simple as the simple mode (where we just a assume the user's intention and remove old versions).
