### ISSUE TITLE
ApkSplits

### ISSUE THREAD

**Issue by chrisjenx** [Triple-T/gradle-play-publisher#140]
Are there plans to support `apkSplit{}`?

If not what would the workaround be? As the plugin only seems to select the first split APK at the moment.

**Comment by scana** [comment]
@bhurling @chrisjenx our team was using 1.2.0-SNAPSHOT version that did support apkSplits for quite some time

Well, until recently at least, as it suddenly stop working few days ago (now it just uploads only the first file)

**Comment by bhurling** [comment]
@scana I am very sorry. I was not aware that someone was actually using that snapshot version in production. I replaced that version by a different branch. My bad.

You have been testing that other version for quite some time I guess. Did you encounter any issues. If not I will merge the two branches and create a new version

**Comment by scana** [comment]
@bhurling please, don't be sorry - it's my fault, using SNAPSHOT on production, right?

Not 100% sure, but I think that we started using it last year, around October. It has been working perfectly fine since then, I don't remember having any issues with it. 
If this is not heavy time-consuming task, then bringing this feature back in either snapshot or some beta release would be fantastic.

To be honest, we can't imagine our lives without it now. I had to upload all of our apk split files manually yesterday and it felt like a terrible chore.

Thanks for the work on that plugin, it's really great! :)

**Comment by chrisjenx** [comment]
:+1:

**Comment by bhurling** [comment]
Merged and released as 1.2.0-beta1. Enjoy.

Let me know if you run into issues.
