### ISSUE TITLE
Add support for linting play resources

### ISSUE THREAD

**Issue by kiall** [Triple-T/gradle-play-publisher#232]
It would be great if it was possible add a optional lint resources task, which could check the length of various strings, ensure graphics are the correct dimenstions etc.

This would great to be able to include in CI, so we know when were overflowing limits or breaking graphics :)

**Comment by SUPERCILEX** [comment]
Did some branch cleanup. Here's the [WIP patch](https://github.com/Triple-T/gradle-play-publisher/files/3303758/Add_new_lint_module_that_provides_Custom_Lint_Rules.zip) from the `validation` branch.

TBH, this issue doesn't seem super relevant to me anymore. This used to be back when the file was potentially trimmed (we always fail now if it's too long). Furthermore, the [first commit to add local validation](https://github.com/Triple-T/gradle-play-publisher/commit/8a8c214c6ff0eeeda2192dcc288fcdb6b1f1a2fe) had no explanation and was probably needed because the Publisher API didn't return useful error messages at the time.

I'm actually leaning towards removing all local validation since it will inevitably become outdated (see #260).
