### ISSUE TITLE
Specify custom location to use for the upload

### ISSUE THREAD

**Issue by jgmGit** [Triple-T/gradle-play-publisher#263]
Is there any way I can use a custom location with the apk name and the gradle task will be uploading the apk file to the console. Not every one uploads the apk from the default location. So it would be good to have something like that.

**Comment by SUPERCILEX** [comment]
No, but running `publishApkRelease` will build the APK for you and put it in the right folder for uploading. Since the plugin requires hooking into the build tasks to work correctly (and that isn't going to change anytime soon), there's no foreseeable plan to let APKs that aren't built on the spot be uploaded.
