### ISSUE TITLE
Add test app with productions keys for anyone to test IRL

### ISSUE THREAD

**Issue by SUPERCILEX** [Triple-T/gradle-play-publisher#282]
Currently, there's no way to ensure the plugin works on a live Google Play account so the best we can do is unit test everything. To fix this, we should add a `live-test` module or something with keys so anyone can test their changes in production. In the future, we could even make this part of our CI builds.

**Comment by SUPERCILEX** [comment]
Turns out this is way harder than I thought because Gradle doesn't let you build, publish, and use a plugin all in the same project. The best I can offer is this dead simple project with full access (except publishing to prod): https://github.com/SUPERCILEX/issue-mcve. Then you can use JitPack to build any commit which makes testing things not _tooo_ bad.

**Comment by gtcompscientist** [comment]
There's really no way for us to make this happen? Seemed like an account with a library application wouldn't be too bad, what's the limitation you found?

**Comment by SUPERCILEX** [comment]
Nope. We are special because we're building an actual _plugin_. If this were a library, we could just add it as a dependency to another module, but the way Gradle works we'd need to build the plugin so it's available for the configuration phase of the other module which isn't a thing.

**Comment by gtcompscientist** [comment]
Oh, I absolutely know how to work around that. It's how I tested the bundle publishing with my projects, and how I got the Gradle version unit test to work.

**Comment by SUPERCILEX** [comment]
Yeah, I tried that but ran into a really weird issue. Here my start for you to work off of: https://github.com/SUPERCILEX/gradle-play-publisher/tree/live-tests. Reassigning.

**Comment by SUPERCILEX** [comment]
Tell me if you get it working!

**Comment by otormaigh** [comment]
You can do this with a separate `settings.gradle.kts` file so that by default you are not referencing (or trying to build) the app module, but in the special case where you want to include the app module to test on live, swap to the other settings file that includes the app module as well as the plugin module in the includes list.

`./gradlew assemble` will build only the plugin module and generate the jar file that the app will eventually depend on, but ignore actually building the app module.
`./gradlew assemble -c special-settings.gradle.kts` will build the app and plugin module.

See here: https://docs.gradle.org/current/userguide/command_line_interface.html#environment_options

Want a PR with a basic setup of this?

**Comment by SUPERCILEX** [comment]
Thanks for the idea! I think the idea was to have something like [this](https://github.com/Triple-T/gradle-play-publisher/blob/771b2a58ad0faf5298e096b9dc2282d08c862929/plugin/src/test/kotlin/com/github/triplet/gradle/play/CompatibilityTest.kt) where we generate and run a build on-the-fly so flagged modules shouldn't be necessary.

**Comment by otormaigh** [comment]
Ah, no worries. I was going off [this](https://github.com/Triple-T/gradle-play-publisher/tree/live-testing) branch, I thought the idea was to have an actual app module as a way to test it and have a sample to for users to reference.

**Comment by SUPERCILEX** [comment]
Did some branch cleanup. Here's the [WIP patch](https://github.com/Triple-T/gradle-play-publisher/files/3303864/Basics_of_a_test_app_.zip) from the `live-testing` branch.

**Comment by SUPERCILEX** [comment]
I have long term plans to split the publishing bits from the gradle bits so that everything can be properly unit tested.
