### ISSUE TITLE
Use new Gradle APIs

### ISSUE THREAD

**Issue by SUPERCILEX** [Triple-T/gradle-play-publisher#373]
This issue is just for keeping track of what we'll want to use when we decide to kill support for old Gradle versions. This won't happen for v2.0.

### 4.7

- [ ] Constructor args for our tasks: https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:passing_arguments_to_a_task_constructor
- [ ] Worker API to parallelize image uploading: https://guides.gradle.org/using-the-worker-api/

### 4.9

- [x] Configuration avoidance for all our tasks: https://docs.gradle.org/current/userguide/task_configuration_avoidance.html

**Comment by oliverlockwood** [comment]
Hi @SUPERCILEX, does this issue cover the following warnings that I'm currently getting?

```
> Task :my-project:generateReleasePlayResources
Some problems were found with the configuration of task ':my-project:generateReleasePlayResources'. Registering invalid inputs and outputs via TaskInputs and TaskOutputs methods has been deprecated and is scheduled to be removed in Gradle 5.0.
 - File '/Users/ogl/work/my-project/src/main/play' specified for property '$1' does not exist.
 - File '/Users/ogl/work/my-project/src/release/play' specified for property '$2' does not exist.
 - File '/Users/ogl/work/my-project/src/release/play' specified for property '$3' does not exist.
```

Or have I missed some part of configuration?  (Note that with my current configuration, builds are being published by your plugin to the Play Store just fine).

Note that I have configured https://docs.gradle.org/4.5/userguide/command_line_interface.html#sec:command_line_warnings to `all` to make this visible, rather than just a summary.

**Comment by SUPERCILEX** [comment]
@oliverlockwood no, but this will: https://github.com/Triple-T/gradle-play-publisher/pull/386. That was my B. 😊

**Comment by SUPERCILEX** [comment]
Constructor args: meh

Worker API: we can't use it to upload anything because the Publisher API isn't serializable. 😢
