### ISSUE TITLE
Support new splits API

### ISSUE THREAD

**Issue by Alexander--** [Triple-T/gradle-play-publisher#39]
Bear in mind, that said API allows developer substantial degree of freedom, so implementation must be flexible as well.

**Comment by bhurling** [comment]
I have never used multiple APKs in any of my projects. Could you tell me a little more about your configuration? What kind of splits do you produce? 

I think, though, that most cases can be expressed by different flavors where each flavor defines some play store filters in its manifest. Provided that flavors share a common package name and correctly calculate their version codes as described here: http://developer.android.com/google/play/publishing/multiple-apks.html#VersionCodes

**Comment by Alexander--** [comment]
I am using per-abi splits (the application consists from native code by large margin, so it greatly reduces total size).

[Android plugin docs](http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits). 

[build.gradle of the app](https://github.com/Alexander--/aria2-android/blob/master/mobile/build.gradle).

**Comment by bhurling** [comment]
Do you think you can achieve the same results by using product flavors instead of splits? There is an option called `ndk.abiFilter` that can be used in flavors. Here is an example where that option is used: http://tools.android.com/tech-docs/new-build-system/tips#TOC-Computing-Version-code-in-multi-flavor-setup

That way you get one publish task for each abi.

**Comment by Alexander--** [comment]
This would be a misuse of flavors and would likely conflict with actual flavors (e.g. Google Play/F-Droid), once I start using them. It's also a waste of resources, because all such "flavors" would have duplicating tasks doing the same thing.

**Comment by Alexander--** [comment]
By the way, instead of tying plugin's internals to exact implementation, could you just gather and handle all PackageApplication tasks upon TaskExecutionGraph creation? E.g. something like:

```
project.afterEvalute {
    // create a single APK upload task
}

project.gradle.taskGraph.whenReady {
    // set inputs of the upload tasks to outputs of every PackageApplication tasks
    // in this project
}
```

If someone does not want to upload all APKs, they should just make your upload task depend on subset of PackageApplication tasks they need.

**Comment by MariusVolkhart** [comment]
This functionality would be epic. Would make multi-apk super easy and basically destroy every excuse left. :+1:

**Comment by bhurling** [comment]
Please check out version 1.2.0-SNAPSHOT. Any feedback is very appreciated.

**Comment by jedi4ever** [comment]
any progress on this? or where can I find the 1.2 branch/code? happy to give it a try

**Comment by bhurling** [comment]
You can define the snapshot repository for your buildscript:

```groovy
buildscript {
    repositories {
        mavenCentral()
        maven {
            url "https://oss.sonatype.org/content/repositories/snapshots/"
        }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0'
        classpath 'com.github.triplet.gradle:play-publisher:1.2.0-SNAPSHOT'
    }
}
```

**Comment by skyisle** [comment]
This works as expected. :100:

**Comment by cawka** [comment]
I've rebased bhurling/splits branch on top of the current master. I also added a small fix to address critical problem in my case.

With the four commits, I was able to successfully publish multiple APKs to google play.

**Comment by jedi4ever** [comment]
thx @cawka

**Comment by rafaltra** [comment]
Any plans to merge changes?

**Comment by bhurling** [comment]
@cawka Do you think that the change I introduced in https://github.com/Triple-T/gradle-play-publisher/commit/8e5a3ff8afd31c0c1f39e8f2e65c5e2c6d429ff0 would work for the splits use case as well?

**Comment by jacek-marchwicki** [comment]
@bhurling 

I tried version `1.2.0-20150712.131046-2` but it seams that does not support `jsonFile = file('keys.json')` (`No such property: jsonFile for class: de.triplet.gradle.play.PlayPublisherPluginExtension_Decorated`).

I think it's because it's build from `bhurling/splits` branch that is behind `master` (  [PlayPublisherPluginExtension](https://github.com/Triple-T/gradle-play-publisher/blob/bhurling/splits/src/main/groovy/de/triplet/gradle/play/PlayPublisherPluginExtension.groovy) )

are you planning to publish version that support apk splits?

BTW: greate plugin, greate work

**Comment by bhurling** [comment]
Merged and released as 1.2.0-beta1.

Let me know if you run into issues

**Comment by jacek-marchwicki** [comment]
@bhurling thans It works, only when you have enabled universalApk it will fail:

```groovy
splits {
        abi {
            enable true
            reset()
            include "armeabi-v7a", "arm64-v8a", "x86", "x86_64", "mips"
            universalApk true // <!-- when "true" it will fail, for "false" will success
        }
    }

applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def versionCodes = ["universal": 0, "armeabi-v7a":1, "mips":2, "arm64-v8a":3, "x86":4, "x86_64":5]
            output.outputFile = new File(
                    output.outputFile.parent,
                    output.outputFile.name.replace(".apk", "-${variant.versionName}.apk"))
            int abiVersionCode = versionCodes.get(output.getFilter(com.android.build.OutputFile.ABI) ?: "universal")
            output.versionCodeOverride = abiVersionCode + android.defaultConfig.versionCode * 10
        }
    }
```

because plugin will try to upload universal apk with other spli apk's and Google play will complain with:

```
:app:publishApkRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:publishApkRelease'.
> com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
  {
    "code" : 403,
    "errors" : [ {
      "domain" : "androidpublisher",
      "message" : "Version 100 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes.",
      "reason" : "multiApkShadowedActiveApk"
    } ],
    "message" : "Version 100 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes."
  }
```

because it will build:
* universal-apk with version 100,
* arm-apk  with version 101,
* arm64-apk with version 102,
* etc...

but `universal-apk` will not contain more abi's so then all other apk versions 101,102...etc

Universal apk is usefull for testing but it would be nice to have some switch to disable upload of this universal apk to Google Play. 

Thanks for all your work!

**Comment by sevar83** [comment]
1.2.0-beta1 works. Thank you very much! Another dream came true. 1 click instead manually upload six APKs 20MB per file!
