### ISSUE TITLE
Add option to customize which flavors/variants get published

### ISSUE THREAD

**Issue by technoir42** [Triple-T/gradle-play-publisher#431]
It's quite common for apps to have development/production flavors or Google Play/non-Google Play flavors while only some of the variants need to be published to the Play Store. Presence of any non-publishable variants makes the combined `publish` task useless.

Right now the only way to disable publishing specific variants is to disable the corresponding tasks once they've been added to the task graph. It'd be great if there was a config option to tell the plugin which variants need to be published.

**Comment by SUPERCILEX** [comment]
This is expected and is unlikely to change for a few reasons:
- Gradle provides native support for not running tasks you don't want: `./gradlew publish -x publishMyVariant`
- You can [disable useless variants](https://developer.android.com/studio/build/build-variants#filter-variants)
- You can create a custom task that depends on only the variants you want

Basically, Gradle already provides built-in mechanisms to deal with your use case. If we see this issue pop up a few more times, we'll reconsider, but for now, I think the options described above are suitable.

**Comment by SUPERCILEX** [comment]
Huh, I didn't think about the accidentally uploading the wrong one thing case. It seems to me like there's a conflict of interest: you basically don't want the global tasks at all, but they're there _specifically to_ publish all variants. Doing otherwise wouldn't be intuitive since no other plugins behave like that.

In your case I almost thing breaking the build is appropriate if the publish task is invoked. I mean, there's no case where you would publish multiple variants together, right? So maybe:
```kt
tasks.named("publish").configure {
    error("Cannot publish all variants at once. Explicitly pick one instead: publishVariant")
}
```

**Comment by Tc2r1** [comment]
In our build process, we build for 40 different variants, only half of those are able to publish to the playstore (which we want). How would we filter the ones that are not able to publish to the play store, yet still have the ability to build all the apks for manual publishing later? 

example: 

MusicTestAppRelease - AutoPublish
HiistoryTestAppRelease - AutoPublish
SportsTestAppRelease - not setup to auto publish
- 37 more of these. 

We'd like to run a publish all command that only publishes the ones that have an account configuration, yet still builds all 40 variants. And doesn't fail due to this.

**Comment by SUPERCILEX** [comment]
@Tc2r1 do you think an enable/disable feature per variant would be useful? If so, please create a new issue from your comment.
