### ISSUE TITLE
Question: Publish multiple flavors at once

### ISSUE THREAD

**Issue by pierx** [Triple-T/gradle-play-publisher#438]
Hi there, thank you very much for this plugin. I've been using it for single variant release which working nicely. However i have question for this flavor builds. I'm using GPP 2.0.0-beta1 and Gradle 4.6.

How exactly we publish multiple product flavors at once? 
I have this multi variant (Nougat, Oreo & Pie), but when running the "publishApk" or "publishBundle" tasks, only the last variant (Pie) are available and activated on the roll out on play console, and the other variant (Nougat and Oreo) are not there on the list for the release and it may only available if we add them manually from the play console library.
How to make all that variant released at once? Am i missing something?

 Thanks in advance!

**Comment by SUPERCILEX** [comment]
Can you show your build file(s)? I'm confused by why you would create a variant for each platform.

**Comment by SUPERCILEX** [comment]
Interesting, will take a look. 👍

**Comment by pierx** [comment]
Thank you very much Alex, appreciate it!

**Comment by SUPERCILEX** [comment]
@pierx Ohhh, right. Product flavors are designed to ship different products. For example, you could have two flavors for two different customers wanting slightly different apps. Because of that, we don't support publishing two different products together. However, we're going to support [publishing combined drafts](https://github.com/Triple-T/gradle-play-publisher/issues/405).

**Comment by SUPERCILEX** [comment]
@pierx Would love your feedback on this: https://github.com/Triple-T/gradle-play-publisher/issues/405#issuecomment-433749766
