### ISSUE TITLE
Add support for non-file based serviceAccountCredentials

### ISSUE THREAD

**Issue by whlk** [Triple-T/gradle-play-publisher#449]
Currently the `serviceAccountCredentials` is of type `file` which is nice if you have the key file in the same repository as the project. Due to security reasons we are not allowed to store secrets in the repository. 

It would be nice if we could supply the `serviceAccountCredentials` as a string (which could be supplied from a secure source as gradle properties):

    play {
       serviceAccountCredentialsJson = System.getProperty('google.play.serviceaccount')
    }

**Comment by whlk** [comment]
Workaround with temporary file:

    File playCredentialsFile = File.createTempFile("temp", ".json")
    playCredentialsFile.deleteOnExit()
    playCredentialsFile.write System.getProperty('google.play.serviceaccount')

    play {
        serviceAccountCredentials = playCredentialsFile
        ...

**Comment by SUPERCILEX** [comment]
@whlk Your current solution is the best available. The problem is that we need to create a [`GoogleCredential`](https://github.com/googleapis/google-auth-library-java/blob/master/oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java) with some custom properties. If we let you give us a pre-built `GoogleCredential`, we wouldn't easily be able to add our properties since there's no copy constructor available. Also, the `GoogleCredential` itself only accepts streams so you'd have to do some weird conversion to get your String into a stream anyway.

Sorry for this non-solution. 😊 If you can think of something better, please let us know!

**Comment by aramosfa** [comment]
Hey! I am trying to implement this in my project and automate publishing using Jenkins, does the workaround that @whlk posted work with Jenkins (ver 1.643), if so can you expand a little on how exactly to make it work? I am unsure how to generate a fake file so that we can build locally, the code above is crashing for me on `playCredentialsFile.write System.getProperty('google.play.serviceaccount')` with an NPE. 

I'm also unsure as to how to supply the correct file using Jenkins. As of right now I have the JSON file containing the service account information as a secret file under  'credentials' in Jenkins but again not sure how to reference through gradle file. 

Any help would be appreciated.  

cc: @SUPERCILEX

**Comment by SUPERCILEX** [comment]
Make sure the property actually has your JSON config.
