### ISSUE TITLE
Suspicious 2.1.1 version

### ISSUE THREAD

**Issue by jrgonzalezg** [Triple-T/gradle-play-publisher#533]
Hi, there is a 2.1.1 version of this plugin on https://plugins.gradle.org/plugin/com.github.triplet.play but there is no mention to that on the code, no version tagged, no release, no changelog and so on. Is that version legit?

**Comment by SUPERCILEX** [comment]
Yes, I published that to fix the [bundle crashes](https://github.com/Triple-T/gradle-play-publisher/issues/516).

The unfortunate reality here is that I've lost all contact with the primary maintainer (who has push access to master). That's why there are a bunch of open PRs. And TBH, I don't really know what to do. 🤷‍♂️ The irony of the situation is that I have publishing access.

My problems aside 😅, the release is straight upload of https://github.com/Triple-T/gradle-play-publisher/pull/526 if I recall correctly. If you're really worried, you can always use JitPack to build any commit in GPP.

**Comment by jrgonzalezg** [comment]
Ok, hope you can eventually contact the maintainer to fix this or get to fork / rename repo in a way that you get full control 😅
