### ISSUE TITLE
Publish without dependencies

### ISSUE THREAD

**Issue by juanibiapina** [Triple-T/gradle-play-publisher#56]
Would it be possible to have a publish task that doesn't depend on the assemble task?

**Comment by bhurling** [comment]
Can you explain your workflow? This plugin is intended to fill the gap between building the APK and publishing it to the play store. 

You might want to take a look at https://github.com/ZeroBrain/gradle-play-publisher that takes an existing APK (instead of extending the build phase). I have never tried it, though, because this is not the use cas I am targeting

**Comment by juanibiapina** [comment]
That's exactly  the use case I have. Thanks for the tip.
