### ISSUE TITLE
Support for OBB files

### ISSUE THREAD

**Issue by mozinator** [Triple-T/gradle-play-publisher#58]
It would be nice to have support for uploading OBB files

**Comment by bhurling** [comment]
Good idea. I think the Google Play Developer API. supports uploading extension files. Do you have a special job that creates the expansion file during the build phase? Or would it be enough to reference the file from within the src/main/play folder? 

Also we should add a flag to control whether or not to upload that file just as we did for the store images.

What do you think?

**Comment by cirorizzo** [comment]
It would be nice, or in meantime have the way to update at least the APK expansion file name on publishing. This is my case, I've already uploaded OBB file but I cannot publish the APK 'cause it will be published without OBB file reference... I just discovered today!!

**Comment by aqibmumtaz** [comment]
I would be desperately waiting for this feature, can any please update on this request?

http://stackoverflow.com/questions/32116479/apk-expansion-files-in-gradle-play-publisher

**Comment by janni2** [comment]
Yes idea with the flag is nice. I think one could consider, that the file is just there. Either created in the build process or just stored statically.

**Comment by aqibmumtaz** [comment]
Hopefully someone could work on it.

**Comment by shiraji** [comment]
I believe creating task with `edits.expansionfiles().upload()` would upload expansion files. Check out #108 and #110, I created lots of tasks. @aqibmumtaz do you want try that? I can help you.

If no one still work with this feature I can implement this in near future. However, since I only have experience with small apps, I have no idea what the OBB file is. Things I know about expansion files are there are 2 obb files you can upload, 2GB max, and one for apk and the other for patching the obb file. Is there any good sample project I can work with, so that I can test the feature. (or is anyone give me steps how I can create the project with generating expansion files during building process?)

**Comment by bhurling** [comment]
Do you think a separate task to upload the expansion file(s) is the best way to go? I think the OBB upload is directly connected to a specific version of the APK. So perhaps it is not wise to separate the extension file upload from an APK upload.

Can anyone shed some light on a typical OBB workflow?
* How often do you update the OBB file?
* Do you use the patch file?
* Wher does that OBB file come from? Do you create it during the build phase or is it rather static?

**Comment by shiraji** [comment]
Yes, definitely I want to know the workflow. If it is clear, I can answer whether creating a separate task to upload the files is good idea or not.

**Comment by Pitel** [comment]
Any progress on this? I also need to assign (already uploaded) obb to apk, but I can't find any way to do this.

**Comment by SUPERCILEX** [comment]
Note to self: the docs are [here](https://developers.google.com/android-publisher/api-ref/edits/expansionfiles/upload).

**Comment by SUPERCILEX** [comment]
I've spoken with some Googlers, and they basically said they're not planning on working on this. Since we can't do anything on our end and app bundles sort of solve the problem, I'm going to close this issue. If the API even adds support for OOB hashes so we aren't reuploading the files on every build, we can reopen.

**Comment by santojon** [comment]
>If the API even adds support for OOB hashes so we aren't reuploading the files on every build, we can reopen.

@SUPERCILEX, This is pretty much what I made in my fork, with success. Used in an app and link the OBB file to APK occurs. No need to re-upload the OBB file each time, just point the version code of already linked existent APK. I'm really happy if can pull request it.

**Comment by SUPERCILEX** [comment]
@santojon the original issue request was to support _uploading_ OOB files. You fork seems to about keeping the OOB file linked with whatever APK is uploaded. Is that right? That feature request doesn't seem too bad.

**Comment by santojon** [comment]
> You fork seems to about keeping the OOB file linked with whatever APK is uploaded. Is that right? That feature request doesn't seem too bad.

@SUPERCILEX Yes, the fork is mainly about keep the link, get OBB link from another yet uploaded APK and attach it to the new one.

I've added some code about upload to, but didn't test yet (I know it's kind of _deprecated_ by App Bundles), and **I can remove if you want.**

Other thing is I've forked from 2.2.1 and I see there is a merge problem with your main branch right now. I've tried to merge, but got problems even in the link.

I will try merge your code into mine again, and, if link a OBB file works, I will pull request it.
