### ISSUE TITLE
Only publish an artifact (apk) and have no build config at all??

### ISSUE THREAD

**Issue by Chris-Marassovich** [Triple-T/gradle-play-publisher#748]
Hello and I hope someone can get me on the right path.

In brief my build is occurring somewhere else so I already have the artifact (apk file) and I simply want to get that file into the Play Store.  My research has lead me to this plugin and it appears it certainly can upload to the Play store.  I have followed the doco but I cannot get it to work.

Is this scenario of starting with an artifact and uploading it without any build config possible with this plugin?  If so I would greatly appreciate some pointers on how to achieve this?

Some details:
My app is a Xamarin Forms app.  I build a iOS and Android target from Xamarin.
I use Team City to perform the builds using msbuild.  
I now want to automate the upload of the APK to the Play Store.
My research has taken me to your plugin and gradle.  I can use gradle as a step in Team City.

I have followed the doco on getting gradle installed and followed the doco on this plugin and this is where things are not going well for me.  The errors I get are quite strange and make no sense to me.  After all I have only just started with gradle and your plugin.  Searching the net for similar errors is not finding much at all.

I have a simple build.gradle file below.
I have pulled this together from the docs and googling.

```
buildscript {
    repositories {
        // ...
        google()
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
    }

    dependencies {
        // ...
        classpath 'com.android.tools.build:builder:3.5.2'
        classpath 'com.android.tools.build:gradle:3.5.3'
    }
}

plugins {
    id 'com.github.triplet.play' version '2.6.1'
}

play {
    track = 'internal'
    serviceAccountEmail = 'me@email.com'
    serviceAccountCredentials = file('Secret.json')
}
```

Simple gradle commands such as
`.\gradlew tasks`
produces errors that make little sense to me.  The output from above command produces

```
.\gradlew tasks

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\<my app name>\build.gradle' line: 26

* What went wrong:
A problem occurred evaluating root project '<my app name>'.
> Could not find method play() for arguments [build_6gwkif72omwtxemektoiuj5pw$_run_closure1@88d365] on root project '<my app name>' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```
I have tried the suggestions but they give me no additional insight.  This is my first time with gradle and this plugin.
My assumption is that this plugin is designed to work off the back of a gradle android build so I am missing large amounts of data and settings that are assumed to be there.

Is it something simple that I am missing in this scenario?
Is it possible that the plugin is not designed to work with simply uploading an APK that is built somewhere else?

Thank you in advance for any help, assistance or direction on this topic.

Regards
Chris ...

**Comment by SUPERCILEX** [comment]
Oh lol, took me a while to figure too, so don't sweat it. I've attached a project that works: [mvp.zip](https://github.com/Triple-T/gradle-play-publisher/files/3938216/mvp.zip)

**Comment by SUPERCILEX** [comment]
Annnnnnnd, here's the fix that makes this error understandable: a6b6b844e26a51aa61e766c88b9abc724751bcd8.

**Comment by Chris-Marassovich** [comment]
@SUPERCILEX.  So fast and on the money with your answer.  Thank you so much.

After I posted this question I did search over GitHub and found projects using the plugin and I started to replicate the build structure (files and folders) and I got it to work and I was about to start removing bits to see what was the minimum.  Your supplied file is exactly what I needed.  Thank you.

One question:
Following the doco I had in my build.gradle
```
plugins {
    id 'com.android.application'
    id 'com.github.triplet.play' version '2.6.1'
}
```
and the com.android.application entry created a lot of errors and issues.  It had me running off in all directions.
Your solution has the following
```
plugins {
    id 'com.github.triplet.play' version '2.6.1'
}

apply plugin: 'com.android.application'
```

What is the reason with your implementation using the "apply plugin" syntax and why is it different to what is in the doco?

Thanks
Chris ...

**Comment by SUPERCILEX** [comment]
@Chris-Marassovich Yeah, that's getting into the nitty gritty of how Gradle works.

The `plugins` block works fine for GPP because we publish our plugin on the [plugin portal](https://plugins.gradle.org/plugin/com.github.triplet.play). But Google being Google, they have their own [maven repo](http://maven.google.com/) for the AGP. This is unfortunate because there are only two places Gradle gets plugins by default: the built-in plugins (`com.gradle.*` namespace) part of the Gradle runtime and the Gradle owned plugin portal mentioned above. You can [get around this](https://gist.github.com/AndrewReitz/b9dbab1336fd1e5080fcc2772fd463d1) by telling Gradle to look for plugins elsewhere, but it's ugly in my opinion.

What does this all mean? When you say
`plugins { id 'com.android.application' version xxx }`, Gradle can't find the plugin because it's not published on the plugin portal. Now you might think that adding the
`buildscript.dependencies.classpath('com.android.tools.build:...')` definition with a
`plugins { id 'com.android.application' }` block would work, but those classpaths aren't shared for the root project.

The two ways of applying plugins are actually [quite different](https://docs.gradle.org/current/userguide/plugins.html#plugins_dsl_limitations): both the `buildscript` and `plugins` block add the plugin's symbols to the build script's classpath, but the `plugins` block is much more powerful because it also applies each plugin immediately, thus adding to Gradle's model (things like the `android` and `play` extension) _before_ the rest of the build script is executed. The key thing to note here is that the `buildscript` block does NOT add to the classpath before the `plugins` block is executed, hence why `plugins { id ... }` can't find anything from `classpath(...)`. Both additions to the classpath happen independently.

To finally answer your question, that's why there are two steps for applying the AGP. First, we have to add to the build script's classpath with `classpath(...)`, then we have to actually configure the plugin and make the `android` extension available by applying the plugin with `apply plugin: ...`. As for why the GPP docs tell you to use the `plugins` block for the AGP, it's because we assume you'll use the standard [multi-module build setup](https://docs.gradle.org/current/userguide/multi_project_builds.html) and apply the AGP in the `:app` module instead of the root module. That works because the `:app` module will be evaluated _after_ the root project, meaning the sub project will have the classpaths from the root module and thus be able to find the AGP within Gradle's runtime.

PS: I just realized I spit out a lot of words, sorry. 😊 I was kinda trying to explain it to myself too, so I hope some of it makes sense.

**Comment by Chris-Marassovich** [comment]
Absolutely and your effort is appreciated.
I quite enjoyed the verbose nature of the content.

thanks

**Comment by l3ender** [comment]
The detail on this issue was very helpful (specifically the mvp example)! I spent multiple hours trying to get the same thing working with our Cordova app which we build separately (.aab) and now want to upload to Google Play using this plugin.

I didn't stumble across this issue until I was creating a separate one to request assistance. Perhaps the readme could be updated to include detail on this type of approach (existing build process and using plugin in standalone manner)? In either case, thank you again for the detail.

For what it's worth, here is my build.gradle. I spent most of my issues trying to work through the Gradle dependency issues (settings file, init file, etc...), which is complicated in our scenario as we use our organization's repository server. Maybe posting the solution here will help someone else.

```
buildscript {
	repositories {
		maven {
			url "http://my.organization.repo/repository/maven-public/"
		}
	}
	dependencies {
		classpath 'com.android.tools.build:gradle:3.5.3'
		classpath "com.github.triplet.gradle:play-publisher:2.6.2"
	}
}

apply plugin: 'com.android.application'
apply plugin: 'com.github.triplet.play'

android {
	compileSdkVersion = 29

	defaultConfig {
		applicationId 'org.myorg.myapp'
	}
}

play {
	serviceAccountCredentials = file("my-creds.json")
	artifactDir = file("../../platforms/android/app/build/outputs/bundle/release")
	defaultToAppBundles = true
}
```

And then invoked like this:
```
-> gradle -b build/android/android_deploy.gradle tasks --group publishing
```

Gradle details:
```
-> gradle -v

------------------------------------------------------------
Gradle 6.0.1
------------------------------------------------------------

Build time:   2019-11-18 20:25:01 UTC
Revision:     fad121066a68c4701acd362daf4287a7c309a0f5

Kotlin:       1.3.50
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_231 (Oracle Corporation 25.231-b11)
OS:           Mac OS X 10.15.3 x86_64
```
