### ISSUE TITLE
Use last release notes when none are specified

### ISSUE THREAD

**Issue by vanniktech** [Triple-T/gradle-play-publisher#763]
As a good default, I'd like to have the last release notes in case I didn't specify anything. This is better than having none at all. As for the selection process, the release notes that were used in the previously highest version code.

**Comment by SUPERCILEX** [comment]
Hmmmm, I've thought of this before but haven't done anything because it's hard to know to know where the release notes should come from. You're suggesting picking from the highest version code, but that wouldn't work for places that automatically generate internal release notes for the internal/alpha channels. Would picking the release channel's previous changelog make sense?

**Comment by vanniktech** [comment]
> Would picking the release channel's previous changelog make sense?

How about the channel we're publishing to? So if we publish `480` to `beta` and there's a changelog for `478` in `beta`, let's pick that one.

**Comment by SUPERCILEX** [comment]
Dope, that's what I was trying to get at. I could do that. 👍

**Comment by vanniktech** [comment]
Dope. Will be sure to test this out with the next release!

**Comment by panpeter** [comment]
@SUPERCILEX at the moment the plugin seems to reuse the latest release notes only when it's a full rollout. Would it be possible to reuse release notes also when it's a staged rollout?

**Comment by SUPERCILEX** [comment]
If there's an API to support that, sure.
