### ISSUE TITLE
Use with Cordova?

### ISSUE THREAD

**Issue by jimthedev** [Triple-T/gradle-play-publisher#78]
Hello there, looks like a great tool. I am a cordova dev which means I know JS and not a ton about gradle (even though my build process relies upon it). I'm wondering if you know of anyone using this in the cordova android build process. Specifically I am interested in using this plugin to upload the apks that cordova spits out. Unfortunately I don't even know where to start. Do you have any gradle resources that might help me to shoehorn this into the cordova build pipeline? If not, no worries, but I figured I'd ask.

Thank you!

**Comment by bhurling** [comment]
You say you are using some kind of gradle plugin to create an APK from your cordova project sources, right? You might want to take a look into the [PlayPublishApkTask](https://github.com/Triple-T/gradle-play-publisher/blob/master/src/main/groovy/de/triplet/gradle/play/PlayPublishApkTask.groovy) and its parent class  [PlayPublishTask](https://github.com/Triple-T/gradle-play-publisher/blob/master/src/main/groovy/de/triplet/gradle/play/PlayPublishTask.groovy). This is where all the magic happens. Those classes basically 

1. set up the connection to the play store (using the credentials provided in the `play` extension)
2. use the Google Play Developer API (specifically an AndroidPublisher.Edits object) to prepare a new release
3. finds the path to the APK (This information can be found in the data structures created by the official Android gradle plugin)
4. commit all the changes

To make it all work there is some wrapper code needed, e.g. a [Properties File](https://github.com/Triple-T/gradle-play-publisher/blob/master/src/main/resources/META-INF/gradle-plugins/com.github.triplet.play.properties) that tells gradle where to find the main plugin class.

As I see it, there is nothing that might stop you from creating a similar plugin for cordova projects

**Comment by warrenc5** [comment]
I had a crack at this, I thought it had a high chance of integration with cordova.  I hit a wall using the cordova plugin framework because of gradle plugin classloaders.

https://github.com/warrenc5/gradle-classloader/ BROKEN

And raised an issue with the good team at gradle.

https://github.com/gradle/gradle/issues/4007

Until that is resolved you'll need to fork the platform cordova-android node package and edit the node_modules/cordova-android/bin/templates/project/app/build.gradle adding your gradle-play-publisher plugin and config.
