### ISSUE TITLE
When promoteArtifact the release note is wrong

### ISSUE THREAD

**Issue by Jintin** [Triple-T/gradle-play-publisher#783]
### Describe the bug

Using wrong release note when promoteArtifact

### How To Reproduce

I have a release in internal channel and promote to alpha via `./gradlew promoteArtifact --from-track internal --promote-track alpha`
But the release not is not using the internal one but the alpha one.

#### Versions

- Gradle Play Publisher: 2.7.2
- Gradle Wrapper: 6.2
- Android Gradle Plugin: 3.6.1

#### Tasks executed

./gradlew promoteArtifact --from-track internal --promote-track alpha

### Expected behavior

The release note should using internal one and better to update local text as well.

**Comment by SUPERCILEX** [comment]
That's expected behavior. First, let me tell you about how things _should_ work with the reasoning attached, then we can figure out if it needs changing. How things work:

- If there are any locally defined release notes (including `default.txt`), always use those.
   - This guarantees consistency. If you have something on your machine, it will be used. Period.
- If no release notes are available locally when uploading new artifacts, look for existing release notes in the Play Console from the same track.
   - This makes keeping release notes along for the ride when iterating on a track easier.
- If no release notes are available locally when promoting artifacts, look for existing release notes in the `promoteTrack`.
   - This prevents ending up with dev release notes in prod. So we don't want alpha/internal release notes to go into beta/prod.

From your perspective, how should it work?

**Comment by Jintin** [comment]
From my perspective, it would be nice if for example:
When we promote from Alpha to Beta, the Beta release note will be override by Alpha, and the play console release note will update together as well.

But never tried the default yet, are you saying the promote task will use `default.txt` to cover existing release note? If so it can cover the major flow but if in some rare scenario it will still work unexpected like you have two working track internal -> alpha and beta -> production in the same time.

Anyway what do you think about the proposal?

**Comment by SUPERCILEX** [comment]
Hmmm, yeah, I think your way actually makes more sense from a conceptual standpoint. Everything is copied over from the `fromTrack`.

**Comment by Jintin** [comment]
Let me know if there's anything I can help, this project is quite interesting.
