### ISSUE TITLE
Support auto resolution strategy in AGP 4.1

### ISSUE THREAD

**Issue by SUPERCILEX** [Triple-T/gradle-play-publisher#790]
Modifying properties after evaluation isn't supported anymore, so we'll have to use the new variant API: https://github.com/ducrohet/versionCode-4.0-sample/blob/22ade6bb5bbe697e022d325ece78232b8af0e32a/buildSrc/src/main/java/com/example/build/CustomPlugin.kt#L34.

**Comment by smworks** [comment]
Is this related to the fact, that versionCode is not updated using auto resolutionStrategy?
The issue is that if I keep deploying using this plugin, app still reports versionCode that was last manually set in build.gradle, even though market shows updated versionCode. Should I expect this issue to be addressed?

**Comment by SUPERCILEX** [comment]
Yup, that's the issue. Once AGP 4.0 goes stable, I should be able to release a version of GPP that uses those new APIs to get auto resolution working again.

**Comment by SUPERCILEX** [comment]
Fixed in 4d52010bfdde024d3e8a2bb16dd26bb42cecea07, 354812b6d789abee4d2c22c598424f73962b54c5
