### ISSUE TITLE
The caller does not have permission

### ISSUE THREAD

**Issue by biswas123** [Triple-T/gradle-play-publisher#805]
Hi Guys,

Could anyone tell me why I get this error? Is it the setup incorrect or the configuration of gradle in my project?

```
* What went wrong:
Execution failed for task ':generateEditForDkDotKeybalanceDotApp'.
> A failure occurred while executing com.github.triplet.gradle.play.tasks.GenerateEdit$Generator
   > 403 Forbidden
     {
       "code" : 403,
       "errors" : [ {
         "domain" : "global",
         "message" : "The caller does not have permission",
         "reason" : "forbidden"
       } ],
       "message" : "The caller does not have permission",
       "status" : "PERMISSION_DENIED"
     }

```

**Comment by SUPERCILEX** [comment]
This is an error in the AndroidPublisher API so there's nothing we can do about it. If you've followed the [setup guide](https://github.com/Triple-T/gradle-play-publisher/blob/master/README.md#service-account), enabled [the API](https://console.cloud.google.com/apis/api/androidpublisher.googleapis.com/overview), and [waited a bit](https://github.com/googleapis/google-api-nodejs-client/issues/1382#issuecomment-466306678) to no avail, I would just contact support since they'll be able to look at your account.

**Comment by SUPERCILEX** [comment]
Actually, just realized the guide doesn't mention enabling the API. Does that fix it for you?

**Comment by Whales1992** [comment]
@khayargoli Pls how did you fix that error? having trouble with it now
