### ISSUE TITLE
Option to upload release one-by-one

### ISSUE THREAD

**Issue by harshmandan** [Triple-T/gradle-play-publisher#814]
### Problem description
I have a massive amount flavours in my project (around 100, and expected to increase). My build system has currently 2 cores and 8 gigs of RAM, SSD (which I know isn't enough, planning to upgrade soon).  But I can't just do one command and leave it to update because as soon as the flavours >30, gradlew throws `Java heap out of space` error.
It takes 3 times of commeting and un-commenting of flavours and waiting in between.

Is there a way to build and publish one bundle at a time. 

### Potential solutions/workarounds
Am I doing this all wrong and should use a CI/CD for publishing all the apps (never used CI). Or is the solution altogether different?

**Comment by SUPERCILEX** [comment]
If you have RAM available, make sure to give it to the JVM: https://github.com/Triple-T/gradle-play-publisher/blob/6b49bc69d9ff65ecca129ca46ae073b9df7b54a3/gradle.properties#L1 (On a large project, `4g` would be good, but you only have a total of 8 gigs so that's probably not going to work.) Disable parallelism `org.gradle.parallel=false` and limit the number of workers `org.gradle.workers.max=2`.

In any case, this isn't something to do on the GPP end.
