### ISSUE TITLE
Variant-based configuration

### ISSUE THREAD

**Issue by JakeWharton** [Triple-T/gradle-play-publisher#86]
Our application publishes the release build type of an 'internal' and 'production' flavor to two different listings on the Play Store. It would be great if the plugin was variant-aware such that we could have `src/internal/play/` and `src/production/play/` be merged with the resources in `src/main/play/` (just like normal code and resources) as well as generate variant-specific tasks (e.g., `publishInternalRelease`, `publishProductionRelease`).

This would also require support for specifying the email and authentication file individually for each variant, as they are under separate accounts.

**Comment by bhurling** [comment]
The first part of this issue is already supported. Every flavor gets its own `play` folder and and its own `publish...Release` tasks. Files in more specific source sets override those in the main source set.

For the second part please see the discussion in #76. My plan is to extend the android plugin to support something similar to signingConfigs:

```
android {
    playAccountConfigs {
        internal {
            serviceAccountEmail ...
            pk12File ...
        }
        production {
            serviceAccountEmail ...
            pk12File ...
        }
    }
    productFlavors {
        internal {
            // ...
            playAccountConfig playAccountConfigs.internal
        }
        production {
            // ...
            playAccountConfig playAccountConfigs.production
        }
    }
}
```

Alternatively, we could just drop some more files into the source sets that contain the account information

**Comment by JakeWharton** [comment]
Oh, I didn't realize the variant folders were supported! I'll admit to only reading the README and poking around the extension definition but not the actual plugin. I did see #76 but filed this separate issue because I assumed variants weren't supported. I'll start watching #76 for updates.

And thanks!
