### ISSUE TITLE
--no-commit for Internal Sharing App

### ISSUE THREAD

**Issue by mochadwi** [Triple-T/gradle-play-publisher#874]
### Problem description

As mentioned in this issue: #831  dry run (`--no-commit`) is for `publish*Bundle` task, but when running `upload*PrivateBundle` this doesn't works

### Potential solutions/workarounds

Able to provide `--no-commit` argument for `upload*PrivateBundle` task

**Comment by SUPERCILEX** [comment]
This can't be supported because the API doesn't use commitable edits for internal sharing uploads. I'm curious, what's your use case? Gradle's native --dry-run might help.

**Comment by mochadwi** [comment]
I see. My usecase was to check if internal sharing build is works, before merging branch development to ready-for-qa branch

Does the `--dry-run` works for that case?

**Comment by SUPERCILEX** [comment]
Do you mean if it builds? That shouldn't need publishing. I'm not sure why you'd want to check that publishing works more than once, but if that's the case, then it's simply not possible to upload an internal sharing artifact without it immediately becoming live. Though for internal artifacts that doesn't matter anyway since nobody but you sees the link to share it.

**Comment by mochadwi** [comment]
I see, thanks @SUPERCILEX closing this issue
