### ISSUE TITLE
Upload native deobfuscation symbols

### ISSUE THREAD

**Issue by bunjix** [Triple-T/gradle-play-publisher#877]
### Problem description
When using native code we might need the symbols files.

### Potential solutions/workarounds
This files can be generated by following the [doc here](https://developer.android.com/studio/build/shrink-code#native-crash-support).
Then we had to upload it manually or with the [Google Play Developper API](https://developers.google.com/android-publisher/api-ref/rest/v3/edits.deobfuscationfiles/upload)

**Comment by SUPERCILEX** [comment]
We already do mapping files, but I didn't realize there were native deobfuscation files too.

**Comment by johnuopini** [comment]
Not having symbols uploaded now also gives an annoying warning in Play Console

**Comment by mariusgherman** [comment]
Would really like this enhancement as well

**Comment by SUPERCILEX** [comment]
Looks like app bundles do this by default. Got this working for APKs on AGP 4.1.

**Comment by SUPERCILEX** [comment]
Since this got a ton of upvotes, y'all can try the snapshot builds until an official release comes out: https://github.com/Triple-T/gradle-play-publisher#snapshot-builds

PS: For whatever reason, the Play Store isn't showing that debug symbols were uploaded, but the API definitely uploaded them. Not sure what's going on there.
