### ISSUE TITLE
Upload key certificate

### ISSUE THREAD

**Issue by hannesa2** [Triple-T/gradle-play-publisher#896]
### Problem description

With V3 I'm forced to switch to json, but I run into 

     {
       "code" : 403,
       "errors" : [ {
         "domain" : "global",
         "message" : "The Android App Bundle was signed with the wrong key. Found: SHA1: 7A:44:..., expected: SHA1: BA:F5:00:5F:0F:06:...",
         "reason" : "forbidden"
       } ],
       "message" : "The Android App Bundle was signed with the wrong key. Found: SHA1: 7A:44:..., expected: SHA1: BA:F5:00:5F:0F:06:..",
       "status" : "PERMISSION_DENIED"
     }
 
I see, Google want the usage of 

![image](https://user-images.githubusercontent.com/3314607/102984740-5140ec00-450e-11eb-8691-c6bad7604d25.png)

But what to do with downloaded `upload_cert.der` ?

### Potential solutions/workarounds

Maybe you have somewhere a guide/wiki how to handle it ?

### Additional context

What I did was (using `upload_cert.der`)

<img width="593" alt="image" src="https://user-images.githubusercontent.com/3314607/102984466-ea233780-450d-11eb-9077-21c0358535b8.png">

but I run into 

> trusted certificate entries are not password-protected 

https://stackoverflow.com/questions/47152473/android-signing-error-trusted-certificate-entries-are-not-password-protected/50875450#50875450 

Does someone has an idea how to handle it to make the  `./gradlew :app:publishBundle -Dorg.gradle.project.track=alpha` work ?

**Comment by SUPERCILEX** [comment]
I think there's some confusion around which keys are used for what.

The error in #897 is a plugin issue. If you run Gradle with the `-S` option, you should see the crash somewhere in the Google http auth code. The weird part is that v3.0 only uses JSON, so I'm not sure how you could have run into that error. Maybe you have several different versions of GPP? And just to check, you're not specifying the removed `serviceAccountEmail` field anywhere, right?

The error in this issue is around apk/bundle singing. So the `signingConfig` code (stuff like `keyAlias`) you put in the other issue is actually this issue. And using JSON authentication to talk to the google play api is the other issue. Normally, if you were able to upload an app with an old version of GPP, switching to JSON auth won't change anything.

The next steps are seeing if you're able to do anything with GPP. If running GPP tasks doesn't crash with authentication errors, then you can work on making sure you're signing your app with the correct key. The easiest way to do that is by using the Play Console directly: it should yell at you with a more informative message. (And that way we're separating whatever the plugin is doing from the app signing.)

**Comment by hannesa2** [comment]
Yes I removed `serviceAccountEmail`.
I was solving by re-trigger CI without doing anything.  So it's still a miracle

Anyway, thank you for your afford looking into this issue.

**Comment by wverdese** [comment]
I have the same problem. The app was signed with the production certificate, as it was before introducing this plugin. In the error message, it shows the correct SHA-1 as "found". The "expected" is the SHA-1 of the Upload key certificate, which I've never noticed until now.

The weirdest part is that it succeeds if I run the gradle task on my machine via a bash script. If I run the same script via a Github action it fails systematically with this error.
